Added exit condition incase of failure

diff --git a/.github/workflows/run-terraform.yaml b/.github/workflows/run-terraform.yaml
--- a/.github/workflows/run-terraform.yaml
+++ b/.github/workflows/run-terraform.yaml
@@ -50,4 +50,6 @@ jobs:
         run: echo "Terraform plan succeeded"
       - name: Check Terraform Plan Status
         if:  steps.plan.outcome == 'failure'
-        run: echo "Terraform plan failed"
+        run: |
+          echo "Terraform plan failed"
+          exit 1
